# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CklDeG22M2vWWwjQ403AkrvKwLDWwIjS

#Refazendo Tudo
"""

def saudacao():
  nome = input('Qual seu nome ?')
  sobre_nome = input ('Qual seu sobrenome ?')
  nome_completo = nome + ' ' + sobre_nome
  print(f' olá {nome_completo} seja bem vindo')

  #Perguntando ao código se posso dirigir.

def verifica_se_posso_dirigir(idade):
  idade = input('Quantos anos voce tem ?')
  idade = int(idade)
  if idade => 18:
    print(f'Você pode dirigir')
  else:
    print(f'Voce ñ pode dirigir')

   
  verifica_se_pode_dirigir()

saudacao()

"""# Minha Primeira Função"""

def saudacao():
  nome = input('Qual seu nome?')
  print(f'olá {nome}')

saudacao()

def nome_completo():
  primeiro_nome = input('Qual o seu primeiro nome?')
  sobrenome = input ('Qual o seu sobrenome?')
  nome_inteiro = primeiro_nome + ' ' + sobrenome
  print(nome_inteiro)

"""#Parâmetros"""

nome = 'lucas'

def saudacao_com_parametro(nome_da_pessoa):
  print(f'Olá {nome_da_pessoa} ' )

saudacao_com_parametro(nome)

"""#Condicional"""

idade = 22

def verifica_se_pode_dirigir(idade):
  if idade >= 18:
    print('Tem permissão para dirigir')
  else:
    print('Não tem permissão para dirigir')

verifica_se_pode_dirigir(idade)

"""#Convertendo tipo para inteiro
```


"""

def verifica_se_pode_dirigir_sem_parametros():
  idade = input('Qual a sua idade?')
  idade = int(idade)
  if idade >= 18:
    print(f'Você tem permissão para dirigir')
  else:
    print(f'Voce ñ tem permissão para dirigir')

verifica_se_pode_dirigir_sem_parametros()



"""#Listas"""

idades = [17, 21, 40, 52]
type(idades)

nome = 'lucas'

type(nome)

idade = 21
type(idade)

idades

idades [-1]

idades[0]

"""#Laços e Loops"""

idades = [18, 22, 15, 50]

#For fora da função

def verifica_se_pode_dirigir(idade):
  if idade >= 18:
    print(f' {idade} anos de idade, Tem permissão para dirigir')
  else:
    print(f' {idade} anos de idade, Não tem permissão para dirigir')

for idade in idades:
  verifica_se_pode_dirigir(idade)

"""# Booleano"""

permissoes = []
idades = [20, 15, 55]

def verifica_se_pode_dirigir(idades, permissoes):
  for idade in idades:
    if idade >= 18:
      permissoes.append(True)
    else:
     permissoes.append(False)

verifica_se_pode_dirigir(idades, permissoes)

permissoes

for permissao in permissoes:
  if permissao == True:
    print('voce pode dirigir')
  else:
    print('vc nao pode dirigir')

"""#Tipos em uma Lista

"""

listas = ['Lucas', 22, True, '20']


for elemento in listas:
  print(f' O elemento  {elemento} é do tipo: ', type(elemento))

"""# Imports"""

from random import randrange, seed

notas_matematica = []

for notas in range(8):
  notas_matematica.append(randrange(0,11))


notas_matematica

"""# MatPlotLib"""

import matplotlib.pyplot as plt

x = list(range(1,9))
y = notas_matematica
plt.plot(x, y, marker='o')
plt.title('Notas Matemáticas')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

